# Generated by Django 5.1 on 2024-11-23 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_phonenumber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageModal',
        ),
    ]
