# Generated by Django 5.1 on 2024-11-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_image_imagemodal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodal',
            name='image',
            field=models.ImageField(max_length=300, upload_to='uploads/'),
        ),
    ]
