# Generated by Django 5.1 on 2024-11-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_imagemodal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodal',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
